<?php

namespace Database\Seeders;

use App\Models\FrequentAskedQuestion;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class FAQSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        FrequentAskedQuestion::create([
            'title' => [
                'en' => 'This text is an example that can be replaced in the same space?',
                'ar' => 'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة؟',
            ],
            'description' => [
                'en' => 'This text is an example that can be replaced in the same space, where you can create this text from the Arabic text generator, where you can generate such text or other texts in addition to increasing the number of characters generated by the application. Arabic text template, Arabic text template, Arabic text template, Arabic text generator is useful for website designers in particular, as the customer here often needs to see an image of the website design. The designer puts temporary texts on the design, the design for the clients form, the role of the Arabic text generator is to save the designer the trouble of searching for text.',
                'ar' => 'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق.إذا كنت تحتاج إلى عدد أكبر من الفقرات يتيح لك مولد النص العربى زيادة عدد الفقرات كما تريد، النص لن يبدو مقسما ولا يحوي أخطاء لغوية، مولد النص العربى مفيد لمصممي المواقع على وجه الخصوص، حيث يحتاج العميل فى كثير من الأحيان أن يطلع على صورة حقيقية لتصميم الموقع.ومن هنا وجب على المصمم أن يضع نصوصا مؤقتة على التصميم ليظهر للعميل الشكل كاملاً،دور مولد النص العربى أن يوفر على المصمم عناء البحث عن نص',
            ],
        ]);

        FrequentAskedQuestion::create([
            'title' => [
                'en' => 'This text is an example that can be replaced in the same space?',
                'ar' =>  'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة؟',
            ],
            'description' => [
                'en' => 'This text is an example that can be replaced in the same space, where you can create this text from the Arabic text generator, where you can generate such text or other texts in addition to increasing the number of characters generated by the application. Arabic text template, Arabic text template, Arabic text template, Arabic text generator is useful for website designers in particular, as the customer here often needs to see an image of the website design. The designer puts temporary texts on the design, the design for the clients form, the role of the Arabic text generator is to save the designer the trouble of searching for text.',
                'ar' => 'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق.إذا كنت تحتاج إلى عدد أكبر من الفقرات يتيح لك مولد النص العربى زيادة عدد الفقرات كما تريد، النص لن يبدو مقسما ولا يحوي أخطاء لغوية، مولد النص العربى مفيد لمصممي المواقع على وجه الخصوص، حيث يحتاج العميل فى كثير من الأحيان أن يطلع على صورة حقيقية لتصميم الموقع.ومن هنا وجب على المصمم أن يضع نصوصا مؤقتة على التصميم ليظهر للعميل الشكل كاملاً،دور مولد النص العربى أن يوفر على المصمم عناء البحث عن نص',
            ],
        ]);
    }
}
